name: CI Pipeline
on:
  push:
    branches:
      - master 
      - feature
jobs:
  build:
    runs-on: [self-hosted, ubuntu-runner, prod]
      
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

    